### ISSUE TITLE
Bug in close dropdown

### ISSUE THREAD

**Issue by Jason0214** [Armour/express-webpack-react-redux-typescript-boilerplate#346]
# I'm submitting a bug report

## Current behavior

when close the dropdown by clicking other area(it wouldn't happen if click on the dropdown button to close it),  there would be an unexpected border on the dropdown button.

![image](https://user-images.githubusercontent.com/19422835/44304733-9b41c200-a396-11e8-8c44-10a09f2ca994.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/19422835/44304736-b01e5580-a396-11e8-8cbe-08e88aba447f.png)

## Minimal reproduction of the problem with instructions

- click the dropdown button to open it
- click other area to close the dropdown list

**Comment by Armour** [comment]
Might be related to Materialize-css

**Comment by Armour** [comment]
I think its fixed.
