### ISSUE TITLE
Yarn error: event-stream

### ISSUE THREAD

**Issue by felipegtx** [Armour/express-webpack-react-redux-typescript-boilerplate#415]
# I'm submitting a
Bug Report

## Temporary fix
As per [this issue](https://github.com/eclipse/che/issues/12077), I've added the following to the `package.json` file and now everything works. Maybe a PR with that is necessary?
```json
"resolutions": {
    "**/event-stream": "^4.0.1"
  }
```

## Current behavior

By running `yarn` on a fresh copy of this repo I get the following error: `error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"`
![image](https://user-images.githubusercontent.com/1022404/51110328-3c229500-17f0-11e9-8841-aee0df37d0ae.png)

## Expected behavior
Yarn should run without any problems.

## Minimal reproduction of the problem with instructions
 - Run `yarn` on a fresh copy of the main branch

## What is the motivation / use case for changing the behavior
 - Using the boilerplate code.

## Environment
 - any.

**Comment by Armour** [comment]
Sure you can send me a PR :)

Also I'm updating lots of dependency pacakges for this repo recently, including react-redux 6 and better i18n structure, probably will finish at the end of this month (when I have time).
